### ISSUE TITLE
"Unsigned plugin" error does not allow to test the component

### ISSUE THREAD

**Issue by ademidoff** [prssanna/grafana-plugin-giphy#1]
I checked out the code base - it mostly looks OK. However, I don't understand how to test it in a docker container. grafana ends up throwing this error "Unsigned plugins were found during plugin initialization. Grafana Labs cannot guarantee the integrity of these plugins."

Any insights?

<img width="1496" alt="Screenshot 2021-08-12 at 20 23 58" src="https://user-images.githubusercontent.com/81549/129241662-d2874ceb-d718-45c1-b891-8cde8557e705.png">

**Comment by prssanna** [comment]
Hi @atymchuk thanks for going through the code! This command should work for now, I've updated the README too:

`docker run -d -p 3000:3000 -v "$(pwd)":/var/lib/grafana/plugins --name=grafana -e "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=prssanna-grafana-giphy-panel" grafana/grafana:7.0.0`

Let me know if it does 😃

**Comment by ademidoff** [comment]
> Hi @atymchuk thanks for going through the code! This command should work for now, I've updated the README too:
> 
> `docker run -d -p 3000:3000 -v "$(pwd)":/var/lib/grafana/plugins --name=grafana -e "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=prssanna-grafana-giphy-panel" grafana/grafana:7.0.0`
> 
> Let me know if it does 😃

Yay, it worked! Closing the issue )
